name: CI/CD - Build and Deploy Trading Bot to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Login to Docker Hub
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_PASS }}" | docker login -u "${{ secrets.DOCKER_HUB_USER }}" --password-stdin

      # Step 3: Build and push Docker image
      - name: Build and Push Docker image
        run: |
          docker build -t nehapansare/trading-bot:latest .
          docker push nehapansare/trading-bot:latest

      # Step 4: SSH into EC2 and deploy
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "🔹 Pulling latest image from Docker Hub..."
            sudo docker pull nehapansare/trading-bot:latest

            echo "🔹 Stopping old container if exists..."
            sudo docker stop trading-bot || true

            echo "🔹 Removing old container..."
            sudo docker rm trading-bot || true

            echo "🔹 Running new container..."
            sudo docker run -d -p 5000:5000 --name trading-bot nehapansare/trading-bot:latest

            echo "✅ Deployment complete!"
            sudo docker ps
